apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lexos-data-pvc
  namespace: lexos
  labels:
    app: lexos-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: fast-ssd  # Adjust based on your storage class

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lexos-models-pvc
  namespace: lexos
  labels:
    app: lexos-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi  # Large storage for AI models
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  namespace: lexos
  labels:
    app: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: fast-ssd